record=52 variable=y truncate=y compress=y key=5 page=1536
   data=y fthreshold=10

position=1 length=12 duplicates=y modifiable=n type=string  
   alternate=y null=n segment=n 

position=13 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=23 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=33 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=43 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 


name=upper.alt 

