record=62 variable=y truncate=y compress=y key=6 page=1536
   data=y fthreshold=10

position=1 length=13 duplicates=n modifiable=n type=string  
   alternate=y null=n segment=n 

position=14 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=24 length=20 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=44 length=8 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=52 length=10 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=62 length=1 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

name=upper.alt
