record=33 variable=y truncate=y compress=y key=3 page=1536
   data=y fthreshold=10

position=1 length=8 duplicates=n modifiable=n type=string  
   alternate=y null=n segment=n 

position=9 length=13 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=22 length=12 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

name=upper.alt
