record=33 variable=y truncate=y compress=y key=4 page=1536
   data=y fthreshold=10

position=1 length=15 duplicates=y modifiable=y type=string  
   alternate=n null=n segment=n 

position=16 length=8 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=24 length=8 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

position=32 length=1 duplicates=y modifiable=y type=string  
   alternate=y null=y value=20 segment=n 

name=upper.alt
