record=30 variable=y truncate=y compress=y key=4 page=1536
   data=y fthreshold=10

position=19 length=12 duplicates=y modifiable=y type=string  
   alternate=y null=n segment=n 

position=3 length=12 duplicates=y modifiable=y type=string  
   alternate=y null=n segment=n 

position=15 length=4 duplicates=y modifiable=y type=string  
   alternate=y null=n segment=n 

position=1 length=30 duplicates=n modifiable=y type=string  
   alternate=y null=n segment=n 


name=upper.alt 

/*segment=n 

position=19 length=12 duplicates=n modifiable=y type=string  
   alternate=y null=n segment=n 

position=1 length=30 duplicates=n modifiable=y type=string  
   alternate=y null=n segment=n 


name=upper.alt 

*/
